apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd-demo
  template:
    metadata:
      labels:
        app: flask-cicd-demo
    spec:
      containers:
        - name: flask-cicd-demo
          image: habassi/flask-cicd-demo:latest
          ports:
            - containerPort: 5000
