apiVersion: v1
kind: Service
metadata:
  name: flask-cicd-demo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: flask-cicd-demo
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32002
